### ISSUE TITLE
Move deletion of old snapshots to a background process/thread

### ISSUE THREAD

**Issue by sdluxeon** [Elders/Cronus#17]

**Comment by mynkow** [comment]
@Elders/cronus-team this is related to the [MSSQL implementation of the EventStore](https://github.com/Elders/Cronus.Persistence.MSSQL). It was not updated since 2015 and to be honest I am not a fan of having the EventStore in a relational database.

I am voting for archivingthe MSSQL event store and closing this issue.

**Comment by mynkow** [comment]
ok, closing then
